//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DontStarve.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cookinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cookinfo()
        {
            this.cookcommentinfo = new HashSet<cookcommentinfo>();
            this.r_material_cookinfo = new HashSet<r_material_cookinfo>();
            this.categoryinfo = new HashSet<categoryinfo>();
            this.everydayrecommendinfo = new HashSet<everydayrecommendinfo>();
        }
    
        public System.Guid Guid_id { get; set; }
        public string Name { get; set; }
        public byte Level { get; set; }
        public bool DelFlag { get; set; }
        public byte Rating { get; set; }
        public long PraiseNum { get; set; }
        public byte[] pic { get; set; }
        public string VideoPath { get; set; }
        public string Remark { get; set; }
        public string Func { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cookcommentinfo> cookcommentinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_material_cookinfo> r_material_cookinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoryinfo> categoryinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<everydayrecommendinfo> everydayrecommendinfo { get; set; }
    }
}
