//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DontStarve.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cookcommentinfo
    {
        public System.Guid Guid_id { get; set; }
        public Nullable<System.Guid> CookId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Content { get; set; }
        public long PraiseNum { get; set; }
    
        public virtual cookinfo cookinfo { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
