//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DontStarve.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dontstarveEntities : DbContext
    {
        private dontstarveEntities()
            : base("name=dontstarveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actioninfo> actioninfo { get; set; }
        public virtual DbSet<categoryinfo> categoryinfo { get; set; }
        public virtual DbSet<cookcommentinfo> cookcommentinfo { get; set; }
        public virtual DbSet<cookinfo> cookinfo { get; set; }
        public virtual DbSet<friendinfo> friendinfo { get; set; }
        public virtual DbSet<materialinfo> materialinfo { get; set; }
        public virtual DbSet<r_material_cookinfo> r_material_cookinfo { get; set; }
        public virtual DbSet<r_user_actioninfo> r_user_actioninfo { get; set; }
        public virtual DbSet<roleinfo> roleinfo { get; set; }
        public virtual DbSet<saysaycommentinfo> saysaycommentinfo { get; set; }
        public virtual DbSet<saysayinfo> saysayinfo { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
    }
}
